### ISSUE TITLE
Sample page error

### ISSUE THREAD

**Issue by iscas-zac** [DongHY1/comments#5]
Hello, I'm from Ruan Yifeng‘s blog, not familiar with frontend system, and simply to try out the comment product. However, when I logged in [the sample page](https://comment.daviddong.me/#), it had an error and couldn't show the comment bar except a quick flash, with the error msg as follows:

```
index-52e8850e.js:40  TypeError: Cannot read properties of undefined (reading '0')
    at tT (index-52e8850e.js:40:300185)
    at eh (index-52e8850e.js:38:19518)
    at zd (index-52e8850e.js:40:3139)
    at Jy (index-52e8850e.js:40:44734)
    at Zy (index-52e8850e.js:40:39724)
    at m1 (index-52e8850e.js:40:39652)
    at Kl (index-52e8850e.js:40:39506)
    at Kd (index-52e8850e.js:40:35874)
    at gm (index-52e8850e.js:40:36677)
    at Wn (index-52e8850e.js:38:3274)
Fd @ index-52e8850e.js:40
Ty.r.callback @ index-52e8850e.js:40
Kp @ index-52e8850e.js:38
pm @ index-52e8850e.js:40
Uy @ index-52e8850e.js:40
f1 @ index-52e8850e.js:40
g1 @ index-52e8850e.js:40
Jn @ index-52e8850e.js:40
gm @ index-52e8850e.js:40
Wn @ index-52e8850e.js:38
(anonymous) @ index-52e8850e.js:40
setTimeout(异步)
(anonymous) @ index-52e8850e.js:17
Bv @ index-52e8850e.js:17
fp @ index-52e8850e.js:17
a @ index-52e8850e.js:17
s @ index-52e8850e.js:17
Dr @ index-52e8850e.js:17
setData @ index-52e8850e.js:17
onSuccess @ index-52e8850e.js:17
f @ index-52e8850e.js:17
Promise.then(异步)
w @ index-52e8850e.js:17
Wv @ index-52e8850e.js:17
fetch @ index-52e8850e.js:17
io @ index-52e8850e.js:17
onSubscribe @ index-52e8850e.js:17
subscribe @ index-52e8850e.js:17
(anonymous) @ index-52e8850e.js:17
fy @ index-52e8850e.js:38
Ic @ index-52e8850e.js:40
ni @ index-52e8850e.js:40
(anonymous) @ index-52e8850e.js:40
T @ index-52e8850e.js:25
j @ index-52e8850e.js:25
index-52e8850e.js:40  Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at tT (index-52e8850e.js:40:300185)
    at eh (index-52e8850e.js:38:19518)
    at zd (index-52e8850e.js:40:3139)
    at Jy (index-52e8850e.js:40:44734)
    at Zy (index-52e8850e.js:40:39724)
    at m1 (index-52e8850e.js:40:39652)
    at Kl (index-52e8850e.js:40:39506)
    at Kd (index-52e8850e.js:40:35874)
    at gm (index-52e8850e.js:40:36677)
    at Wn (index-52e8850e.js:38:3274)
```

![image](https://github.com/DongHY1/comments/assets/92451907/1b1078db-d81d-4331-9748-e052cd393f1a)

My browser is Edge 120.

**Comment by hidaviddong** [comment]
@iscas-zac  Thank you for providing such detailed error information! The issue is due to this piece of code:


`profileData[0].profile_info.avatar_url`

Here, the `profileData` array is empty, which causes a failure in fetching user information. I will fix it in the next version. For now, you could try clearing the Supabase localStorage in your browser and logging in again with GitHub. If you still have any issues, please feel free to leave a message!

**Comment by iscas-zac** [comment]
it's still there, if I didn't misunderstand "clearing the Supabase localStorage in your browser". I suppose I only need to click into developer tool and clear the localStorage? Anyway, I'm glad that this issue helps.

**Comment by hidaviddong** [comment]
> it's still there, if I didn't misunderstand "clearing the Supabase localStorage in your browser". I suppose I only need to click into developer tool and clear the localStorage? Anyway, I'm glad that this issue helps.

@iscas-zac  i fixed it this bug , now when profile_info is empty, a default avatar will be displayed

![CleanShot 2023-12-19 at 10 34 40](https://github.com/DongHY1/comments/assets/73568310/10451470-85d6-4376-8333-846913263040)

**Comment by iscas-zac** [comment]
OK, I see the result. Thanks!
